/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as StatsRouteImport } from "./routes/stats";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as FlashcardsRouteImport } from "./routes/flashcards";
import { Route as IndexRouteImport } from "./routes/index";

const StatsRoute = StatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: "/flashcards",
  path: "/flashcards",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/flashcards": typeof FlashcardsRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/flashcards": typeof FlashcardsRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/flashcards": typeof FlashcardsRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/flashcards" | "/settings" | "/stats";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/flashcards" | "/settings" | "/stats";
  id: "__root__" | "/" | "/flashcards" | "/settings" | "/stats";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FlashcardsRoute: typeof FlashcardsRoute;
  SettingsRoute: typeof SettingsRoute;
  StatsRoute: typeof StatsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/stats": {
      id: "/stats";
      path: "/stats";
      fullPath: "/stats";
      preLoaderRoute: typeof StatsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/flashcards": {
      id: "/flashcards";
      path: "/flashcards";
      fullPath: "/flashcards";
      preLoaderRoute: typeof FlashcardsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsRoute: FlashcardsRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
